# Generated by Django 5.0.4 on 2026-03-07 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_history', to='documents.document')),
            ],
            options={
                'ordering': ['-asked_at'],
                'indexes': [models.Index(fields=['document', 'asked_at'], name='documents_q_documen_de9226_idx')],
            },
        ),
    ]
